version: '3'
services:
  # api:
  #   build: ./
  #   ports:
  #     - 3333:5555
  #   env_file:
  #     - config.yaml
  #   restart: always
  db:
    image: postgres:bullseye
    container_name: postgres_bullseye
    ports:
      - 4444:5432
    shm_size: 128mb
    environment:
      - POSTGRES_USER=admin0001
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=pgdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgsite
      
  pg4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    networks:
      - pgsite
    depends_on:
      - db


volumes:
  pgdata:

networks:
  pgsite: