version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:5555
    environment:
      - APP_PORT=5555
      - DB_USERNAME=admin0001
      - DB_PASSWORD=admin1234
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DBNAME=appdb
    entrypoint: entrypoint
    depends_on:
      - pg4
    restart: always
    
  db:
    image: postgres:bullseye
    ports:
      - 4444:5432
    shm_size: 128mb
    environment:
      - POSTGRES_USER=admin0001
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgsite
      
  pg4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 9090:90
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    networks:
      - pgsite
    depends_on:
      - db


volumes:
  pgdata:

networks:
  pgsite: