services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:5555
    environment:
      - APP_MODE=release
    env_file:
      - .env
    entrypoint: /app_api
    depends_on:
      - db
    # restart: unless-stopped
    restart: on-failure
    networks:
      - pgsite
    
  db:
    image: postgres:bullseye
    container_name: db_server
    ports:
      - 4444:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgsite


volumes:
  pgdata:

networks:
  pgsite: